# Generated by Django 2.2.7 on 2019-11-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.CharField(max_length=30)),
                ('arrival', models.CharField(max_length=30)),
                ('price', models.FloatField(default=174.2)),
                ('time_of_departure', models.TimeField()),
                ('time_of_arrival', models.TimeField()),
                ('date_of_departure', models.DateField()),
                ('date_of_arrival', models.DateField()),
                ('business_class_ticket_num', models.IntegerField()),
                ('economy_class_ticket_num', models.IntegerField()),
            ],
        ),
    ]
